### ISSUE TITLE
Introduce {REALM} parameter for SignalFX METRICS_STORE

### ISSUE THREAD

**Issue by amsin02** [spinnaker/kayenta#549]
Hi,
I tried using **SignalFX** as my **metric source**. But, Kayenta could not access my account, since no **{REALM}** setting it available in Kayenta, so by default, it queries **us0** realm of SignalFX. I have my account in **us1** realm. Hence, it was throwing an error. I had to change the [SignalFXConfiguration.java](https://github.com/spinnaker/kayenta/blob/2f83ca9416eca99efa40a56c32ce8a30ce1e373c/kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxConfiguration.java
) 
![Signalfxconfig](https://user-images.githubusercontent.com/50662104/58856490-710c8700-86c0-11e9-97f2-0f551601c6eb.PNG)

to set the **endpoint URI** from

```https://stream.signalfx.com```  
to 
 ```https://stream.us1.signalfx.com```

===============================

**For SignalFX realm overview:**:
[SignalFlow Overview](https://developers.signalfx.com/signalflow_analytics/signalflow_overview.html)

**Comment by fieldju** [comment]
@amsin02 got it,

In my [original PR there was a comment thread about this](https://github.com/spinnaker/kayenta/pull/385#discussion_r225203024) but at the time I couldn't find evidence that it wasn't static.

I can update the config to add a new field like [the Datadog account config](https://github.com/spinnaker/kayenta/blob/master/kayenta-datadog/src/main/java/com/netflix/kayenta/datadog/config/DatadogManagedAccount.java#L36) to [the SignalFx account config](https://github.com/spinnaker/kayenta/blob/master/kayenta-signalfx/src/main/java/com/netflix/kayenta/signalfx/config/SignalFxManagedAccount.java#L28)

It can default to `https://stream.signalfx.com` if not supplied, to maintain backwards compatibility.

ex:
```
  signalfx:
    enabled: true
    accounts:
    - name: sfx-architecture
      accessToken: HM6mJwwXukcb4Ryw3lBdvg
      defaultScopeKey: server_group
      defualtLocationKey: server_region
      streamEndpoint: https://my-override.com
      supportedTypes:
      - METRICS_STORE
```
