### ISSUE TITLE
Prometheus query issue : kayenta builds same query for canary & baseline : relates to #540

### ISSUE THREAD

**Issue by amsin02** [spinnaker/kayenta#553]
Hey,
I tried using Prometheus as me METRIC_STORE. But, Kayenta makes the same query for canary and baseline even after supplying all the parameters.

**kayenta.yml**
```
  prometheus:
    enabled: true
    accounts:
      - name: prometheus-account
        endpoint:
          baseUrl: http://localhost:9090
        supportedTypes:
          - METRICS_STORE
        defaultScopeKey: server_group
        defualtLocationKey: server_region
```
===============================================

**Execution Request**

```
 "executionRequest": {
    "analysisIntervalMins": 2,
    "beginAfterMins": 0,
    "lifetimeDurationMins": 10,
    "lookbackMins":0,
    "scopes": [
      {
        "controlScope": "baseline",
        "experimentScope": "canary",
        "scopeName": "default",
        "step": 10
      }
    ],
    "siteLocal": {},
    "thresholds": {
      "marginal": 95.0,
      "pass": 75.0
    }
  }
```
================================================

I checked the **metricSetListId** which I got in the response to check what queries it is making to Prometheus.

**MetricSetListQueries**
```
"attributes": {
      "control": {
        "query": "rate(num_of_error_requests[1m])"
      },
      "experiment": {
        "query": "rate(num_of_error_requests[1m])"
      }
```
===================================================

whereas for **SignalFX**, it supports different queries for canary & baseline for the same execution request:

**MetricSetListQueries**
```
"attributes":{ 
"control": { 
 "signal-flow-program": "data('num_of_success_requests', filter=filter('server_group','baseline')).sum(by=['server_group']).publish()" },

 "experiment": {
 "signal-flow-program" :  "data('num_of_success_requests', filter=filter('server_group', 'canary')).sum(by=['server_group']).publish()"}
}
```
