### ISSUE TITLE
Support multiple metric backends

### ISSUE THREAD

**Issue by noamhurwitz** [spinnaker/kayenta#730]
I've currently enabled both Prometheus and Stackdriver in the canary config, but when using Kayenta through Deck I'm only able to retrieve metrics from the former. According to [1] I should be able to access Stackdriver metrics as well but I am not able to.

[1] https://cloud.google.com/solutions/automated-canary-analysis-kubernetes-engine-spinnaker

Config:
```
canary:
    enabled: true
    serviceIntegrations:
    - name: google
      enabled: true
      accounts:
      - name: {{GOOGLE_NAME}}
        project: {{PROJECT}}
        bucket: {{BUCKET}}
        rootFolder: kayenta
        supportedTypes:
        - METRICS_STORE
        - CONFIGURATION_STORE
        - OBJECT_STORE
      gcsEnabled: true
      stackdriverEnabled: true
    - name: prometheus
      enabled: true
      accounts:
      - name: {{PROM_NAME}}
        endpoint:
          baseUrl: http://{{PROM_URL}}
        supportedTypes:
        - METRICS_STORE
```
