### ISSUE TITLE
Kayenta configuration to suport Azure Storage as persistent storage.

### ISSUE THREAD

**Issue by robeferre** [spinnaker/kayenta#816]
Hi guys I hope you are doing fine, how can I configure azure storage to persist kayenta data, we are not allowed to use another cloud provider,  I have seen a configuration here and some at the internet but I have not seen any documentation related to deploy using halyard, I sent some time researching and didnt find anything, I tried to load the configuration using local profiles but didnt work as well. Any help will be appretiated, Cheers.

**Comment by tillig** [comment]
You might have better luck getting traction on docs and Halyard [in the Spinnaker main issues repo](https://github.com/spinnaker/spinnaker/issues). I haven't found much traffic in here and sometimes wonder if this issues list was left open by accident.

We deploy Kayenta as a standalone service outside of Spinnaker using Helm charts and I've got Azure Storage working. I plan on blogging it soon, but in the meantime...

Let's say you create a storage account called `mykayentastorage`. Inside that storage account, you have to create a storage container for Kayenta, so we'll call that `kayentacontainer`. Finally, you _must enable HTTP access_. This is not on by default. I opened #786 a while ago to see if we can switch this to HTTPS but haven't gotten a response; I think I'll just submit the PR and hope for the best. Anyway, be sure to enable HTTP on that storage account. That's a huge gotcha.

Then, inside your `kayenta.yml` you should have something like this:

```yml
azure:
  enabled: true
  accounts:
    - name: canary-storage
      storageAccountName: mykayentastrorage
      accountAccessKey: big-long-key-from-azure-portal
      container: kayentacontainer
      rootFolder: kayenta
      endpointSuffix: core.windows.net
      supportedTypes:
        - OBJECT_STORE
        - CONFIGURATION_STORE
```

I can't tell you where in your .halyard folder to put that nor can I help you get any traction on getting Halyard itself to handle this for you. I just know I got this working with standalone Kayenta so thought it could help.
