### ISSUE TITLE
Support Keptn SLIs as a data source

### ISSUE THREAD

**Issue by jetzlstorfer** [spinnaker/kayenta#818]
Would love to see an integration to have [Keptn](https://keptn.sh) service-level indicators (SLIs) as a data-source and base the canary analysis upon the data that is received. 
Even better if it would be possible to use the Keptn quality gates (based on service-level objectives) directly for the decision on the canary. 

Keptn SLIs are a way to abstract from the actual data provider by building a "library" of SLIs, for example for Prometheus:
```
---
spec_version: '1.0'
indicators:
  cpu_usage: avg(rate(container_cpu_usage_seconds_total{namespace="$PROJECT-$STAGE",pod_name=~"$SERVICE-primary-.*"}[5m]))
  response_time_p95: histogram_quantile(0.95, sum by(le) (rate(http_response_time_milliseconds_bucket{handler="ItemsController.addToCart",job="$SERVICE-$PROJECT-$STAGE-canary"}[$DURATION_SECONDS])))
```

In the SLO file or in the Kayenta configuration it would then be possible to just refer to the name of the indicator to get the value. Keptn will take care how to actually retrieve the value and there is no configuration in Spinnaker needed.
